name: live_coding
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  toast: ^0.3.0
  google_fonts: ^6.2.1
  overlay_support: ^2.1.0
  dio: ^5.4.0
  logger: ^2.0.2+1
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  bot_toast: ^4.1.3
  flutter_iconly: ^1.0.2
  fl_chart: ^0.66.0
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  path: ^1.8.3
  flutter_native_splash: ^2.3.9
  hooks_riverpod: ^2.4.9
  highlight_text:
  flutter_flavorizr: ^2.2.1
  country_flags: ^2.2.0
  expandable_page_view: ^1.0.17
  pinput: ^3.0.1
  mask_text_input_formatter: ^2.8.0
  radix_icons: ^1.0.1
  image_cropper: ^5.0.1
  file_picker: ^6.1.1
  #  file_saver: ^0.2.9
  image_picker: ^1.0.7
  external_path: ^1.0.3
  flutter_native_image: ^0.0.6+1
  permission_handler: ^11.3.0
  http: ^1.2.0
  path_provider: ^2.1.2
  google_maps_flutter: ^2.5.3
  geolocator: ^8.0.0
  flutter_google_places_sdk: ^0.3.7
  flutter_polyline_points: ^2.0.0
  geocoding: ^3.0.0
  open_geocoder: ^0.0.1
  custom_info_window: ^1.0.1
  webview_flutter: ^4.5.0
  flutter_chat_bubble: ^2.0.2
  chat_bubbles: ^1.6.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_database: ^10.4.9
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/svgs/
    - assets/images/pngs/
    - assets/fonts/

  fonts:
    - family: DM Sans Black
      fonts:
        - asset: assets/fonts/DMSans-Black.ttf
    - family: DM Sans Bold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
    - family: DM Sans Light
      fonts:
        - asset: assets/fonts/DMSans-Light.ttf
    - family: DM Sans Medium
      fonts:
        - asset: assets/fonts/DMSans-Medium.ttf
    - family: DM Sans Regular
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: DM Sans Thin
      fonts:
        - asset: assets/fonts/DMSans-Thin.ttf
    - family: DM Sans SemiBold
      fonts:
        - asset: assets/fonts/DMSans-SemiBold.ttf
    - family: DM Sans ExtraLight
      fonts:
        - asset: assets/fonts/DMSans-ExtraLight.ttf
    - family: DM Sans ExtraBold
      fonts:
        - asset: assets/fonts/DMSans-ExtraBold.ttf
